version: '3'

services:
  api:
    build: api
    command: gunicorn main:"test_app()" -b 0.0.0.0:5000 --reload
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"

  client:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    depends_on:
      - api

volumes:
  node-modules:
  postgres_data: